/* Write your T-SQL query statement below */
SELECT employee_id FROM EMPLOYEES
WHERE SALARY < 30000
AND MANAGER_ID IS NOT NULL
AND MANAGER_ID NOT IN (SELECT EMPLOYEE_ID FROM EMPLOYEES)
ORDER BY EMPLOYEE_ID