/* Write your T-SQL query statement below */
SELECT P.product_id, ISNULL(ROUND(SUM(1.0*P.PRICE*U.UNITS)/SUM(1.0*U.UNITS),2),0) AS average_price 
FROM PRICES P 
LEFT JOIN UNITSSOLD U ON P.PRODUCT_ID = U.PRODUCT_ID
AND P.START_DATE <= U.PURCHASE_DATE AND U.PURCHASE_DATE <= P.END_DATE
GROUP BY P.PRODUCT_ID