/* Write your T-SQL query statement below */
SELECT ACTIVITY_DATE AS day, COUNT(DISTINCT USER_ID) AS active_users
FROM ACTIVITY
WHERE ACTIVITY_DATE BETWEEN '2019-06-28' AND '2019-07-27'
GROUP BY ACTIVITY_DATE