/* Write your T-SQL query statement below */
SELECT product_name, SUM(unit) AS unit FROM PRODUCTS P 
INNER JOIN ORDERS O ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE YEAR(ORDER_DATE) = 2020 AND MONTH(ORDER_DATE) = 2
GROUP BY PRODUCT_NAME
HAVING SUM(UNIT) >= 100
