/* Write your T-SQL query statement below */
SELECT S.user_id, ISNULL(ROUND((
    (SELECT COUNT(USER_ID )
    FROM CONFIRMATIONS C
    WHERE ACTION = 'confirmed' AND S.USER_ID = C.USER_ID
    GROUP BY USER_ID) * 1.0
    /
    COUNT(C2.USER_ID) * 1.0
),2),0) AS confirmation_rate
FROM SIGNUPS S
LEFT JOIN CONFIRMATIONS C2
ON S.USER_ID = C2.USER_ID
GROUP BY S.USER_ID