/* Write your T-SQL query statement below */
SELECT A.MACHINE_ID, ROUND(AVG(B.TIMESTAMP - A.TIMESTAMP) ,3) AS processing_time FROM ACTIVITY AS A, ACTIVITY AS B
WHERE A.ACTIVITY_TYPE = 'start' AND B.ACTIVITY_TYPE = 'end'
AND A.MACHINE_ID = B.MACHINE_ID AND A.PROCESS_ID = B.PROCESS_ID
GROUP BY A.MACHINE_ID