/* Write your T-SQL query statement below */
SELECT R.contest_id, 
ROUND(COUNT(DISTINCT USER_ID)*100.0/(
    SELECT COUNT(USER_ID) FROM USERS
), 2) AS percentage 
FROM REGISTER R
GROUP BY R.CONTEST_ID
ORDER BY percentage DESC,
CONTEST_ID